"""Add products, scrapes, product_data tables and remove cards table

Revision ID: 83d3ae23dadf
Revises: c982c5fc6739
Create Date: 2024-10-29 21:32:03.476045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83d3ae23dadf'
down_revision: Union[str, None] = 'c982c5fc6739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cards_id', table_name='cards')
    op.drop_index('ix_cards_name', table_name='cards')
    op.drop_table('cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rarity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cards_pkey')
    )
    op.create_index('ix_cards_name', 'cards', ['name'], unique=False)
    op.create_index('ix_cards_id', 'cards', ['id'], unique=False)
    # ### end Alembic commands ###
